### ISSUE TITLE
Cli: open ./template/python: no such file or directory error

### ISSUE THREAD

**Issue by theodesp** [alexellis/faas-cli#99] opened 2017-09-14 08:06 UTC
I'm trying to build a python example using the tutorial https://blog.alexellis.io/first-faas-python-function/ and the moment I call:

```
$ faas-cli -action build -f ./stack.yml
```

I get:

```
open ./template/python: no such file or directory error
```

is there anything that I miss?

## Expected Behaviour

```
$ faas-cli -action build -f ./stack.yml
...

Successfully tagged faas-hello-python:latest  
Image: faas-hello-python built.  
```

## Current Behaviour

```
➜  functions cat stack.yml
provider:
  name: faas
  gateway: http://localhost:8080

functions:
  hello-python:
    lang: python
    handler: ./hello-python
    image: faas-hello-python
```

```
➜  functions cat hello-python/handler.py
def handle(req):
    print("Hello! You said: " + req)
    %
```

```
➜  functions faas-cli -action build -f ./stack.yml
Building: hello-python.
Clearing temporary build folder: ./build/hello-python/
Preparing ./hello-python/ ./build/hello-python/function
2017/09/14 08:57:26 open ./template/python: no such file or directory
```
## Steps to Reproduce (for bugs)

1. 
2.
3.
4.

## Context

I was trying to follow the tutorial steps from here:
https://blog.alexellis.io/first-faas-python-function/

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

```
➜  functions docker version
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:12:06 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:19 2017
 OS/Arch:      linux/amd64
 Experimental: true
```
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Docker swarm
* Operating System and version (e.g. Linux, Windows, MacOS):

```
➜  functions uname -a
Darwin C02SG3FQFVH6 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
```
* Link to your project or a code example to reproduce issue:

**Comment by aafrey** [comment] 2017-09-14 08:34
@theodesp I was unable to reproduce, using the commands you had listed. There have been some updates to the cli recently though, what version are you using? `faas-cli version`

and you might also try running the below commands to see if you have better luck.
```
$ mkdir hello-python && cd hello-python
$ faas-cli new --lang python --name hello-python
$ faas-cli build -f ./hello-python.yml
```

**Comment by rgee0** [comment] 2017-09-14 18:32
@theodesp I managed to replicate but only through running the `faas-cli` command in the wrong place.  

The blog post suggests using the user's home directory so the lay out of files should be:

~/functions
├── hello-python
│   └── handler.py
└── stack.yml

The `faas-cli -action build -f ./stack.yml` command should then be run from the functions directory.

**Comment by rgee0** [comment] 2017-09-14 18:32
derek add label support question

**Comment by rgee0** [comment] 2017-09-14 18:33
Derek add label: Support Question

**Comment by alexellis** [comment] 2017-09-14 19:27
As long as you don't have a template folder already, the templates are always downloaded every time you run a "build" or "new" command via the CLI.

**Comment by alexellis** [comment] 2017-09-14 19:29
Here's an example:

```
$ faas-cli new --lang python --name test1
2017/09/14 12:28:40 No templates found in current directory.
2017/09/14 12:28:40 Attempting to expand templates from master.zip
Found "template/"
....
```

**Comment by alexellis** [comment] 2017-09-15 16:49
Closing the issue. If anyone has more information feel free to re-open / comment here.

**Closed** 2017-09-15 16:49 UTC
Labels: Support Question
